import { useMemo, useState } from 'react';
import { SHOWCASE_ISLANDS, TRANSFERS, type ShowcaseNode } from './hdd-showcase-data';

const NODE_W=108, NODE_H=58;
const ROW_TOP={temporal:55,ensemble:345,operations:635} as const;
const X=(depth:number)=>155+depth*152;
const Y=(node:ShowcaseNode)=>ROW_TOP[node.island]+node.y;
const curve=(a:ShowcaseNode,b:ShowcaseNode)=>`M${X(a.depth)+NODE_W} ${Y(a)+NODE_H/2} C${X(a.depth)+142} ${Y(a)+NODE_H/2},${X(b.depth)-34} ${Y(b)+NODE_H/2},${X(b.depth)} ${Y(b)+NODE_H/2}`;

function IslandGraph({selectedId,onSelect}:{selectedId:string;onSelect:(node:ShowcaseNode)=>void}){
 const all=SHOWCASE_ISLANDS.flatMap(i=>i.nodes); const byId=useMemo(()=>new Map(all.map(n=>[n.id,n])),[all]);
 return <svg viewBox="0 0 1280 920" className="min-h-[720px] w-full" aria-label="三岛协同算法进化图"><defs>
  <marker id="edge-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#aab5c3"/></marker>
  <marker id="ok-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#18966f"/></marker>
  <marker id="bad-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#d84b5b"/></marker>
 </defs>
 {SHOWCASE_ISLANDS.map(island=><g key={island.key}><rect x="18" y={ROW_TOP[island.key]} width="1244" height="255" rx="16" fill={island.key==='temporal'?'#f5f9ff':island.key==='ensemble'?'#faf8ff':'#f4fbf8'} stroke={`${island.color}33`}/><circle cx="52" cy={ROW_TOP[island.key]+31} r="6" fill={island.color}/><text x="68" y={ROW_TOP[island.key]+36} fontSize="15" fontWeight="700" fill="#172033">{island.name}</text><text x="35" y={ROW_TOP[island.key]+58} fontSize="10.5" fill="#64748b">{island.focus}</text>
  {island.nodes.filter(n=>n.parentId).map(n=>{const p=byId.get(n.parentId!);return p?<path key={`${p.id}-${n.id}`} d={curve(p,n)} fill="none" stroke={n.state==='failed'?'#d96a76':n.state==='pruned'?'#c0a45c':'#aab5c3'} strokeWidth="1.5" strokeDasharray={n.state==='failed'||n.state==='pruned'?'5 4':undefined} markerEnd="url(#edge-arrow)"/>:null})}</g>)}
 {TRANSFERS.map((t,i)=>{const a=byId.get(t.from),b=byId.get(t.to);if(!a||!b)return null;const ok=t.outcome==='成功',x1=X(a.depth)+NODE_W/2,y1=Y(a)+NODE_H,x2=X(b.depth)+NODE_W/2,y2=Y(b),bend=i%2?46:-46;return <g key={t.label}><path d={`M${x1} ${y1} C${x1+bend} ${(y1+y2)/2},${x2+bend} ${(y1+y2)/2},${x2} ${y2}`} fill="none" stroke={ok?'#18966f':'#d84b5b'} strokeWidth="2.2" strokeDasharray={ok?undefined:'7 5'} markerEnd={ok?'url(#ok-arrow)':'url(#bad-arrow)'}/><rect x={(x1+x2)/2-48} y={(y1+y2)/2-12} width="96" height="20" rx="10" fill={ok?'#e8f7f1':'#fff0f1'}/><text x={(x1+x2)/2} y={(y1+y2)/2+2} textAnchor="middle" fontSize="9.5" fontWeight="700" fill={ok?'#13795b':'#b83243'}>{ok?'注入成功':'注入失败'} · {t.gain}</text></g>})}
 {all.map(node=>{const selected=node.id===selectedId,island=SHOWCASE_ISLANDS.find(i=>i.key===node.island)!;const stroke=node.state==='best'?'#e4a11b':node.state==='failed'?'#d84b5b':node.state==='pruned'?'#b49439':selected?island.color:'#bac5d2';return <g key={node.id} transform={`translate(${X(node.depth)} ${Y(node)})`} onClick={()=>onSelect(node)} className="cursor-pointer" role="button" tabIndex={0}><rect width={NODE_W} height={NODE_H} rx="8" fill="#fff" stroke={stroke} strokeWidth={selected||node.state==='best'?2.5:1.2} opacity={node.state==='pruned'?.78:1}/><circle cx="11" cy="12" r="4" fill={node.state==='best'?'#e4a11b':node.state==='failed'?'#d84b5b':node.state==='pruned'?'#b49439':island.color}/><text x="20" y="15" fontSize="9.5" fontWeight="700" fill="#334155">{node.id}</text><text x="9" y="31" fontSize="9.5" fontWeight="700" fill="#172033">ROS {node.score.toFixed(2)}</text><text x="66" y="31" fontSize="8.5" fill={node.delta>=0?'#138a67':'#c43d4e'}>Δ {node.delta>=0?'+':''}{node.delta.toFixed(2)}</text><text x="9" y="46" fontSize="8.5" fill="#526075">Q {node.q.toFixed(2)}</text><text x="51" y="46" fontSize="8.5" fill="#526075">Jev {node.jev.toFixed(2)}</text><text x="9" y="56" fontSize="7.5" fill="#718096">{node.title}</text></g>})}
 </svg>;
}

export function HddEvolutionShowcase(){
 const all=SHOWCASE_ISLANDS.flatMap(i=>i.nodes);const[selectedId,setSelectedId]=useState('T6');const selected=all.find(n=>n.id===selectedId)??all[0];const island=SHOWCASE_ISLANDS.find(i=>i.key===selected.island)!;const stateLabel={progress:'继续进化',best:'全局最优',failed:'评估失败',pruned:'停止扩展'}[selected.state];
 return <div className="flex flex-col gap-3" data-judge-evolution><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-xl font-semibold text-fg">KGTE 三岛协同进化图</h1><p className="mt-1 text-xs text-fg-muted">三棵非对称搜索树同时展开：分支竞争、噪声剪枝、失败回退与跨岛知识注入均保留在演化轨迹中。</p></div><div className="flex gap-4 text-xs text-fg-muted"><span><strong className="text-fg">33</strong> 个候选</span><span><strong className="text-danger-700">13</strong> 次停止/失败</span><span><strong className="text-success-700">36.50</strong> 最佳 ROS</span></div></header>
 <section className="overflow-x-auto rounded-xl border border-border-subtle bg-white"><div className="flex flex-wrap items-center gap-4 border-b border-border-subtle px-4 py-2 text-[11px] text-fg-muted"><strong className="text-fg">点击任意节点查看完整判定</strong><span>实线：继续进化</span><span className="text-warning-700">虚线黄：剪枝</span><span className="text-danger-700">虚线红：失败</span><span className="text-success-700">绿色跨层线：注入成功</span></div><IslandGraph selectedId={selected.id} onSelect={(node)=>setSelectedId(node.id)}/></section>
 <section className="grid gap-3 lg:grid-cols-[340px_1fr]"><aside className="rounded-lg border border-border-subtle bg-surface p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><div><p className="font-mono text-xs font-semibold" style={{color:island.color}}>{selected.id} · {island.name}</p><h2 className="mt-1 text-base font-semibold text-fg">{selected.title}</h2></div><span className={`rounded-full px-2 py-1 text-[11px] font-medium ${selected.state==='failed'?'bg-danger-50 text-danger-700':selected.state==='pruned'?'bg-warning-50 text-warning-700':'bg-success-50 text-success-700'}`}>{stateLabel}</span></div><dl className="mt-4 grid grid-cols-4 gap-2 border-y border-border-subtle py-3">{[['ROS',selected.score.toFixed(2)],['Δ',`${selected.delta>=0?'+':''}${selected.delta.toFixed(2)}`],['Q',selected.q.toFixed(2)],['Jev',selected.jev.toFixed(2)]].map(([l,v])=><div key={l}><dt className="text-[10px] text-fg-subtle">{l}</dt><dd className="tabular text-base font-semibold text-fg">{v}</dd></div>)}</dl><p className="mt-3 text-xs leading-5 text-fg-muted">{selected.reflection}</p></aside>
 <div className="rounded-lg border border-border-subtle bg-surface p-4"><h2 className="text-sm font-semibold text-fg">跨岛知识注入记录</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{TRANSFERS.map(t=><button type="button" key={t.label} onClick={()=>setSelectedId(t.to)} className={`rounded-md border p-3 text-left ${t.outcome==='成功'?'border-success-500/30 bg-success-50':'border-danger-500/30 bg-danger-50'}`}><div className="flex items-center justify-between"><span className="text-xs font-semibold text-fg">{t.label}</span><strong className={t.outcome==='成功'?'text-success-700':'text-danger-700'}>{t.outcome}</strong></div><p className="mt-1 font-mono text-[10px] text-fg-muted">{t.from} → {t.to} · {t.gain}</p></button>)}</div></div></section></div>;
}
