const METRICS = [
  ['Precision', '0.281'], ['Recall', '0.537'], ['F1', '0.369'], ['AUPRC', '0.340'],
  ['误告率 FAR', '0.34%'], ['漏告率 MDR', '46.3%'], ['有效节点率', '90.5%'], ['运行耗时', '2,024 s'],
] as const;

export function HddResultsCase() {
  return <div className="flex flex-col gap-5" data-hdd-results>
    <header><h1 className="text-xl font-semibold text-fg">HDD 验证结果</h1><p className="mt-1 text-xs text-fg-muted">同一评估协议下，从固定初始程序出发完成候选生成、本地评测与闭环进化。</p></header>
    <section className="grid gap-3 md:grid-cols-4"><div className="rounded-lg border border-brand-200 bg-brand-50 p-4"><p className="text-xs text-brand-700">初始 ROS</p><strong className="mt-2 block text-3xl text-fg">22.81</strong></div><div className="rounded-lg border border-success-500/30 bg-success-50 p-4"><p className="text-xs text-success-700">最佳 ROS</p><strong className="mt-2 block text-3xl text-success-700">36.50</strong></div><div className="rounded-lg border border-border-subtle bg-surface p-4"><p className="text-xs text-fg-muted">绝对提升</p><strong className="mt-2 block text-3xl text-fg">+13.69</strong></div><div className="rounded-lg border border-border-subtle bg-surface p-4"><p className="text-xs text-fg-muted">总 Token</p><strong className="mt-2 block text-3xl text-fg">119,205</strong></div></section>
    <section className="grid gap-4 xl:grid-cols-[1fr_0.75fr]"><div className="rounded-lg border border-border-subtle bg-surface p-4"><h2 className="text-sm font-semibold text-fg">最佳候选评测指标</h2><div className="mt-3 grid grid-cols-2 gap-x-6 sm:grid-cols-4">{METRICS.map(([label,value]) => <div key={label} className="border-t border-border-subtle py-3"><p className="text-[11px] text-fg-subtle">{label}</p><strong className="mt-1 block text-lg text-fg">{value}</strong></div>)}</div></div><div className="rounded-lg border border-border-subtle bg-surface p-4"><h2 className="text-sm font-semibold text-fg">结论可信度</h2><ul className="mt-3 space-y-3 text-xs leading-5 text-fg-muted"><li>✓ 分数仅由本地 evaluator 产生</li><li>✓ 原始数据、标签与模型权重不离开本地</li><li>✓ 节点改进经过噪声门与 Jev 辅助判断</li><li>✓ 失败迁移和负结果完整保留</li></ul></div></section>
    <section className="rounded-lg border border-border-subtle bg-surface p-4"><h2 className="text-sm font-semibold text-fg">最优方案演化摘要</h2><div className="mt-3 grid gap-2 md:grid-cols-4">{[['时序特征','引入窗口末端、趋势及变化率'],['模型策略','知识注入与异质模型组合'],['阈值策略','围绕误告预算完成阈值校准'],['可信闭环','本地评测反馈驱动下一轮搜索']].map(([title,text],i) => <div key={title} className="rounded-md bg-surface-muted p-3"><span className="text-[10px] font-semibold text-brand-600">0{i+1}</span><h3 className="mt-1 text-xs font-semibold text-fg">{title}</h3><p className="mt-1 text-[11px] leading-5 text-fg-muted">{text}</p></div>)}</div></section>
    <section className="rounded-lg border border-border-subtle bg-surface p-4"><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="text-sm font-semibold text-fg">最终算法交付物</h2><p className="mt-1 text-[11px] text-fg-muted">代码与说明文件均来自本次运行的可下载制品目录。</p></div><span className="rounded-full bg-success-50 px-2.5 py-1 text-[11px] font-medium text-success-700">2 项完整制品</span></div><div className="mt-4 grid gap-3 lg:grid-cols-2">
      <article className="overflow-hidden rounded-lg border border-border-subtle bg-white"><div className="flex items-start justify-between gap-3 p-4"><div><p className="font-mono text-[10px] text-brand-600">program-n18a3b4dd</p><h3 className="mt-1 text-sm font-semibold text-fg">最终候选代码 · n18a3b4dd.py</h3></div><a href={artifactDownloadUrl(SHOWCASE_RUN_ID,'program-n18a3b4dd')} download="n18a3b4dd.py" className="fe-btn fe-btn-primary fe-btn-sm shrink-0">下载完整代码</a></div><div className="grid gap-2 border-t border-border-subtle bg-surface-muted p-4 text-[11px] sm:grid-cols-2"><div><span className="text-fg-subtle">模型</span><strong className="mt-1 block text-fg">Balanced Logistic Regression</strong></div><div><span className="text-fg-subtle">输入特征</span><strong className="mt-1 block text-fg">归一化 SMART 窗口特征</strong></div><div><span className="text-fg-subtle">关键参数</span><strong className="mt-1 block font-mono text-fg">C=0.943 · max_iter=200</strong></div><div><span className="text-fg-subtle">输出</span><strong className="mt-1 block font-mono text-fg">score + alarm@0.55</strong></div></div><pre className="overflow-x-auto border-t border-border-subtle bg-[#172033] p-4 text-[10px] leading-5 text-slate-200"><code>{`features = history.filter(regex="smart_.*_normalized")\nmodel = LogisticRegression(class_weight="balanced", C=0.943)\nscore = model.predict_proba(query)[:, 1]\nalarm = (score >= 0.55).astype(int)`}</code></pre></article>
      <article className="rounded-lg border border-border-subtle bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] text-brand-600">final_algorithm_README.md</p><h3 className="mt-1 text-sm font-semibold text-fg">最终算法说明文件</h3></div><a href={artifactDownloadUrl(SHOWCASE_RUN_ID,'report-final_algorithm_README.md')} download="FaultEvolve-HDD-final-algorithm.md" className="fe-btn fe-btn-secondary fe-btn-sm shrink-0">下载完整说明</a></div><p className="mt-4 text-xs leading-5 text-fg-muted">说明文件包含交付物清单、算法结构、关键超参数、命令行运行方式、输入输出字段、数据安全边界与复现要求。</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{[['执行接口','--data-dir / --split / --out'],['缺失值处理','归一化特征统一填充'],['类别不平衡','class_weight=balanced'],['数据边界','训练、推理与评测均在本地']].map(([label,value])=><div key={label} className="rounded-md bg-surface-muted p-3"><span className="text-[10px] text-fg-subtle">{label}</span><strong className="mt-1 block text-[11px] leading-5 text-fg">{value}</strong></div>)}</div><p className="mt-4 rounded-md border border-brand-500/20 bg-brand-50 p-3 text-[11px] leading-5 text-fg-muted">复现时使用与验证运行相同的数据切分、依赖版本和本地 evaluator；成绩以结果页记录的评测证据为准。</p></article>
    </div></section>
  </div>;
}
import { artifactDownloadUrl } from '@/lib/artifact-url';
import { SHOWCASE_RUN_ID } from './hdd-showcase-data';
